# Luna Sol – sol variant
# Alacritty theme  (TOML format, Alacritty ≥ 0.12)

[colors.primary]
background        = "#1B1D26"
foreground        = "#D7D7D7"
bright_foreground = "#E9E9E9"

[colors.cursor]
text   = "#1B1D26"
cursor = "#D7D7D7"

[colors.vi_mode_cursor]
text   = "#1B1D26"
cursor = "#D4B96A"

[colors.search.matches]
foreground = "#1B1D26"
background = "#5E697E"

[colors.search.focused_match]
foreground = "#1B1D26"
background = "#D4B96A"

[colors.hints.start]
foreground = "#1B1D26"
background = "#D4B96A"

[colors.hints.end]
foreground = "#1B1D26"
background = "#7EC4DE"

[colors.selection]
text       = "#D7D7D7"
background = "#5E697E"

[colors.normal]
black   = "#14161D"
red     = "#D4956A"
green   = "#6DCFA8"
yellow  = "#C8B55E"
blue    = "#7EC4DE"
magenta = "#D4B96A"
cyan    = "#B8A0EE"
white   = "#D7D7D7"

[colors.bright]
black   = "#272932"
red     = "#E05555"
green   = "#6ECFA8"
yellow  = "#E8A05A"
blue    = "#6CAEC0"
magenta = "#E8717E"
cyan    = "#7EC4DE"
white   = "#E9E9E9"

[colors.footer_bar]
foreground = "#D7D7D7"
background = "#14161D"
