-- luna/theme.lua
-- Complete highlight group definitions for the Luna colorscheme.
-- Structured identically to oh-lucy's theme.lua but greatly extended.

local config  = require("luna.config")

local M = {}

function M.setup(colors)
  local c   = colors
  local cfg = config
  local transparent = cfg.transparent_background

  -- Helper
  local function bg(col) return transparent and "NONE" or col end

  -- ═══════════════════════════════════════════════════════════════
  --  BASE EDITOR
  -- ═══════════════════════════════════════════════════════════════
  local editor = {
    -- Utility styles
    Bold      = { bold = true },
    Italic    = { italic = true },
    Underline = { underline = true },

    -- Core editor
    Normal        = { fg = c.fg,       bg = bg(c.bg) },
    NormalFloat   = { fg = c.fg,       bg = c.bg_float },
    NormalNC      = { fg = c.fg_bright, bg = bg(c.bg) },
    NormalSB      = { fg = c.fg,       bg = c.bg_sidebar },

    ColorColumn   = { bg = c.black1 },
    Conceal       = { fg = c.fg },
    CursorColumn  = {},
    CursorLine    = { bg = c.bg_cursorline },
    CursorLineNr  = { fg = c.white, bg = c.gutter_bg, bold = true },
    Cursor        = { fg = c.yellow, bg = c.bg },
    lCursor       = { fg = c.cursor_fg, bg = c.cursor_bg },
    TermCursor    = { fg = c.cursor_fg, bg = c.cursor_bg },
    TermCursorNC  = { fg = c.cursor_fg, bg = c.cursor_bg },

    LineNr        = { fg = c.line_nr, bg = bg(c.line_bg) },
    SignColumn    = { bg = bg(c.line_bg) },
    FoldColumn    = { fg = c.line_nr, bg = c.bg },
    Folded        = { fg = c.white,   bg = c.gray0 },

    -- Status / tab / win
    StatusLine    = { fg = c.bg_dark, bg = c.gray_punc },
    StatusLineNC  = { fg = c.bg_dark, bg = c.gray_punc },
    StatusLineTerm   = { fg = c.green_func, bg = c.black },
    StatusLineTermNC = { fg = c.gray_punc,  bg = c.black },
    TabLine       = { fg = c.line_nr },
    TabLineFill   = { fg = c.line_nr },
    TabLineSel    = { fg = c.fg },
    VertSplit     = { fg = c.vsplit },
    WinSeparator  = { fg = c.vsplit, bg = bg(c.bg) },

    -- Menus / popups
    Pmenu         = { fg = c.white1, bg = c.black },
    PmenuSel      = { fg = c.fg, bg = c.gray1 },
    PmenuSbar     = { bg = c.gray0 },
    PmenuThumb    = { bg = c.black },
    WildMenu      = { fg = c.fg },

    -- Selection / search
    Visual        = { bg = c.bg_visual, bold = true },
    VisualNOS     = { fg = c.selection_fg, bg = c.selection_bg },
    Search        = { fg = c.line_nr, bg = c.orange },
    IncSearch     = { fg = c.bg, bg = c.orange },
    Substitute    = { fg = c.gray2, bg = c.orange },
    MatchParen    = { fg = c.white1, bg = c.black },
    MatchParenCur = { underline = true },
    MatchWord     = { underline = true },
    MatchWordCur  = { underline = true },

    -- Messages
    ModeMsg       = { fg = c.fg, bg = c.bg },
    MsgArea       = { fg = c.fg, bg = bg(c.bg) },
    MsgSeparator  = { fg = c.fg, bg = c.bg },
    MoreMsg       = { fg = c.orange_warn },
    WarningMsg    = { fg = c.orange_warn },
    ErrorMsg      = { fg = c.gray0, bg = c.red_err, bold = true },
    Question      = { fg = c.green_func },
    QuickFixLine  = { fg = c.orange_warn },

    -- Misc
    NonText       = { fg = c.gray2 },
    Whitespace    = { fg = c.non_text },
    SpecialKey    = { fg = c.gray_punc, bold = true },
    Directory     = { fg = c.white },
    Title         = { fg = c.gray_punc },
    EndOfBuffer   = { fg = c.non_text },
    FloatBorder   = { fg = c.gray2, bg = c.black },
    WinBar        = { fg = c.fg, bg = bg(c.bg) },
    WinBarNC      = { fg = c.comment, bg = bg(c.bg) },

    -- ─── Syntax ─────────────────────────────────────────────────
    Boolean       = { fg = c.boolean, italic = cfg.italic_booleans },
    Character     = { fg = c.yellow },
    Comment       = { fg = c.comment, italic = cfg.italic_comments },
    Conditional   = { fg = c.red_key_w },
    Constant      = { fg = c.pink },
    Debug         = { fg = c.fg },
    Define        = { fg = c.blue_type },
    Delimiter     = { fg = c.gray_punc },
    Exception     = { fg = c.white },
    Float         = { fg = c.orange },
    Function      = { fg = c.green_func, italic = cfg.italic_functions },
    Identifier    = { fg = c.white1, italic = cfg.italic_variables },
    Ignore        = { fg = c.gray_punc },
    Include       = { fg = c.blue_type },
    Keyword       = { fg = c.red_key_w, italic = cfg.italic_keywords },
    Label         = { fg = c.red_key_w },
    Macro         = { fg = c.blue_type },
    Number        = { fg = c.orange },
    Operator      = { fg = c.white },
    PreCondit     = { fg = c.blue_type },
    PreProc       = { fg = c.blue_type },
    Repeat        = { fg = c.red_key_w },
    Special       = { fg = c.gray_punc },
    SpecialChar   = { fg = c.yellow },
    SpecialComment= { fg = c.pink },
    Statement     = { fg = c.red_key_w },
    StorageClass  = { fg = c.blue_type },
    String        = { fg = c.yellow },
    Structure     = { fg = c.green_func },
    Tag           = { fg = c.gray_punc },
    Todo          = { fg = c.yellow, bold = true },
    Type          = { fg = c.blue_type },
    Typedef       = { fg = c.blue_type },
    Variable      = { fg = c.white },

    -- Errors / spelling
    Error         = { fg = c.red_key_w, bg = c.bg, bold = true },
    SpellBad      = { fg = c.red_key_w, underline = true },
    SpellCap      = { fg = c.orange,    underline = true },
    SpellLocal    = { fg = c.green,     underline = true },
    SpellRare     = { fg = c.pink,      underline = true },

    -- Diff (editor level)
    DiffAdd     = { fg = c.green_func },
    DiffAdded   = { fg = c.green_func },
    DiffChange  = { fg = c.green_func },
    DiffDelete  = { fg = c.red_key_w },
    DiffRemoved = { fg = c.red_key_w },
    DiffText    = { fg = c.white1 },
    DiffFile    = { fg = c.pink },

    -- ─── Markdown ───────────────────────────────────────────────
    markdownBold              = { fg = c.white, bold = true },
    markdownCode              = { fg = c.orange },
    markdownCodeBlock         = { fg = c.orange },
    markdownCodeDelimiter     = { fg = c.green },
    markdownCodeError         = { fg = c.red_err },
    markdownCodeSpecial       = { fg = c.orange },
    markdownH1                = { fg = c.white, bold = true },
    markdownH2                = { fg = c.white, bold = true },
    markdownH3                = { fg = c.white },
    markdownH4                = { fg = c.white },
    markdownH5                = { fg = c.white },
    markdownH6                = { fg = c.white },
    markdownHeadingDelimiter  = { fg = c.white },
    markdownHeadingRule       = { fg = c.accent },
    markdownId                = { fg = c.pink },
    markdownIdDeclaration     = { fg = c.white },
    markdownIdDelimiter       = { fg = c.gray2 },
    markdownItalic            = { fg = c.white, italic = true },
    markdownLinkDelimiter     = { fg = c.gray2 },
    markdownLinkText          = { fg = c.white },
    markdownListMarker        = { fg = c.red_key_w },
    markdownOrderedListMarker = { fg = c.red_key_w },
    markdownBlockquote        = { fg = c.accent },
    markdownRule              = { fg = c.accent },
    markdownUrl               = { fg = c.pink, underline = true },
    markdownUrlTitleDelimiter = { fg = c.white },

    -- ─── Treesitter (legacy @-capture names) ────────────────────
    ["@annotation"]              = { fg = c.yellow },
    ["@attribute"]               = { fg = c.white },
    ["@boolean"]                 = { fg = c.pink, italic = cfg.italic_booleans },
    ["@character"]               = { fg = c.yellow },
    ["@character.special"]       = { fg = c.yellow },
    ["@comment"]                 = { fg = c.comment, italic = cfg.italic_comments },
    ["@conditional"]             = { fg = c.red_key_w },
    ["@constant"]                = { fg = c.pink },
    ["@constant.builtin"]        = { fg = c.pink },
    ["@constant.macro"]          = { fg = c.blue_type },
    ["@constructor"]             = { fg = c.white },
    ["@define"]                  = { fg = c.red_key_w },
    ["@error"]                   = { fg = c.red_err, bg = c.bg, bold = true },
    ["@exception"]               = { fg = c.red_key_w },
    ["@field"]                   = { fg = c.white },
    ["@float"]                   = { fg = c.pink },
    ["@function"]                = { fg = c.green_func, italic = cfg.italic_functions },
    ["@function.builtin"]        = { fg = c.green_func },
    ["@function.call"]           = { fg = c.green_func },
    ["@function.macro"]          = { fg = c.blue_type },
    ["@include"]                 = { fg = c.red_key_w },
    ["@keyword"]                 = { fg = c.red_key_w, italic = cfg.italic_keywords },
    ["@keyword.function"]        = { fg = c.red_key_w, italic = cfg.italic_keywords },
    ["@keyword.operator"]        = { fg = c.red_key_w },
    ["@keyword.return"]          = { fg = c.red_key_w },
    ["@label"]                   = { fg = c.pink },
    ["@method"]                  = { fg = c.green_func },
    ["@method.call"]             = { fg = c.green_func },
    ["@namespace"]               = { fg = c.blue_type },
    ["@none"]                    = { fg = c.orange },
    ["@number"]                  = { fg = c.pink },
    ["@operator"]                = { fg = c.red_key_w },
    ["@parameter"]               = { fg = c.white },
    ["@parameter.reference"]     = { fg = c.white },
    ["@preproc"]                 = { fg = c.red_key_w },
    ["@property"]                = { fg = c.white },
    ["@punctuation.bracket"]     = { fg = c.gray_punc },
    ["@punctuation.delimiter"]   = { fg = c.gray_punc },
    ["@punctuation.special"]     = { fg = c.gray_punc },
    ["@repeat"]                  = { fg = c.red_key_w },
    ["@storageclass"]            = { fg = c.blue_type },
    ["@string"]                  = { fg = c.yellow },
    ["@string.escape"]           = { fg = c.boolean },
    ["@string.regex"]            = { fg = c.yellow },
    ["@symbol"]                  = { fg = c.white },
    ["@tag"]                     = { fg = c.red_key_w },
    ["@tag.attribute"]           = { fg = c.white },
    ["@tag.delimiter"]           = { fg = c.gray_punc },
    ["@text"]                    = { fg = c.fg },
    ["@text.emphasis"]           = { italic = true },
    ["@text.literal"]            = { fg = c.yellow },
    ["@text.reference"]          = { fg = c.pink },
    ["@text.strong"]             = { fg = c.yellow, bold = true },
    ["@text.title"]              = { fg = c.white, bold = true },
    ["@text.todo"]               = { fg = c.orange, bold = true },
    ["@text.underline"]          = { underline = true },
    ["@text.uri"]                = { fg = c.yellow, underline = true },
    ["@text.warning"]            = { fg = c.orange_warn },
    ["@todo"]                    = { fg = c.orange, bold = true },
    ["@type"]                    = { fg = c.blue_type },
    ["@type.builtin"]            = { fg = c.red_key_w },
    ["@type.definition"]         = { fg = c.red_key_w },
    ["@type.qualifier"]          = { fg = c.red_key_w },
    ["@variable"]                = { fg = c.white, italic = cfg.italic_variables },
    ["@variable.builtin"]        = { fg = c.pink },

    -- ─── Treesitter v3 (new dot-separated capture names) ────────
    ["@variable.member"]         = { fg = c.white },
    ["@variable.parameter"]      = { fg = c.white },
    ["@module"]                  = { fg = c.blue_type },
    ["@module.builtin"]          = { fg = c.red_key_w },
    ["@string.special.url"]      = { fg = c.yellow, underline = true },
    ["@markup.heading"]          = { fg = c.white, bold = true },
    ["@markup.heading.1"]        = { fg = c.pink, bold = true },
    ["@markup.heading.2"]        = { fg = c.blue_type, bold = true },
    ["@markup.heading.3"]        = { fg = c.green_func, bold = true },
    ["@markup.heading.4"]        = { fg = c.yellow, bold = true },
    ["@markup.heading.5"]        = { fg = c.orange_warn, bold = true },
    ["@markup.heading.6"]        = { fg = c.white },
    ["@markup.raw"]              = { fg = c.orange },
    ["@markup.link"]             = { fg = c.pink, underline = true },
    ["@markup.link.label"]       = { fg = c.white },
    ["@markup.link.url"]         = { fg = c.yellow, underline = true },
    ["@markup.list"]             = { fg = c.red_key_w },
    ["@markup.list.checked"]     = { fg = c.green_func },
    ["@markup.list.unchecked"]   = { fg = c.gray_punc },
    ["@markup.italic"]           = { italic = true },
    ["@markup.strong"]           = { bold = true },
    ["@markup.underline"]        = { underline = true },
    ["@markup.strikethrough"]    = { strikethrough = true },
    ["@markup.quote"]            = { fg = c.comment, italic = true },
    ["@diff.plus"]               = { fg = c.green_func },
    ["@diff.minus"]              = { fg = c.red_key_w },
    ["@diff.delta"]              = { fg = c.blue_type },
  }

  -- ═══════════════════════════════════════════════════════════════
  --  PLUGINS
  -- ═══════════════════════════════════════════════════════════════
  local plugins = {

    -- ─── nvim-treesitter-context ────────────────────────────────
    TreesitterContext            = { bg = c.bg_cursorline },
    TreesitterContextLineNumber  = { fg = c.gray_punc, bg = c.bg_cursorline },
    TreesitterContextBottom      = { underline = true, sp = c.gray_punc },

    -- ─── LSP / Diagnostics ──────────────────────────────────────
    DiagnosticError              = { fg = c.red_err },
    DiagnosticWarn               = { fg = c.orange_warn },
    DiagnosticInfo               = { fg = c.yellow },
    DiagnosticHint               = { fg = c.blue_type },
    DiagnosticOk                 = { fg = c.green_func },

    DiagnosticVirtualTextError   = { fg = c.red_err },
    DiagnosticVirtualTextWarn    = { fg = c.orange_warn },
    DiagnosticVirtualTextInfo    = { fg = c.yellow },
    DiagnosticVirtualTextHint    = { fg = c.gray2 },

    DiagnosticFloatingError      = { fg = c.red_err },
    DiagnosticFloatingWarn       = { fg = c.orange_warn },
    DiagnosticFloatingInfo       = { fg = c.yellow },
    DiagnosticFloatingHint       = { fg = c.blue_type },

    DiagnosticSignError          = { fg = c.red_err,    bg = c.line_bg },
    DiagnosticSignWarn           = { fg = c.orange_warn, bg = c.line_bg },
    DiagnosticSignInfo           = { fg = c.yellow,     bg = c.line_bg },
    DiagnosticSignHint           = { fg = c.blue_type,  bg = c.line_bg },

    DiagnosticUnderlineError     = { underline = true, sp = c.red_err },
    DiagnosticUnderlineWarn      = { underline = true, sp = c.orange_warn },
    DiagnosticUnderlineInfo      = { underline = true, sp = c.yellow },
    DiagnosticUnderlineHint      = { underline = true, sp = c.blue_type },

    -- Deprecated (pre-0.6) LSP diagnostic groups kept for compat
    LspDiagnosticsDefaultError            = { fg = c.red_err },
    LspDiagnosticsDefaultWarning          = { fg = c.yellow },
    LspDiagnosticsDefaultInformation      = { fg = c.yellow },
    LspDiagnosticsDefaultHint             = { fg = c.blue_type },
    LspDiagnosticsError                   = { fg = c.red_err },
    LspDiagnosticsFloatingError           = { fg = c.red_err },
    LspDiagnosticsFloatingHint            = { fg = c.blue_type },
    LspDiagnosticsFloatingInformation     = { fg = c.yellow },
    LspDiagnosticsFloatingWarning         = { fg = c.orange_warn },
    LspDiagnosticsHint                    = { fg = c.blue_type },
    LspDiagnosticsInformation             = { fg = c.yellow },
    LspDiagnosticsSignError               = { fg = c.red_err },
    LspDiagnosticsSignHint                = { fg = c.blue_type },
    LspDiagnosticsSignInformation         = { fg = c.yellow },
    LspDiagnosticsSignWarning             = { fg = c.orange_warn },
    LspDiagnosticsUnderlineError          = { underline = true },
    LspDiagnosticsUnderlineHint           = { underline = true },
    LspDiagnosticsUnderlineInformation    = { underline = true },
    LspDiagnosticsUnderlineWarning        = { underline = true },
    LspDiagnosticsVirtualTextHint         = { fg = c.gray2 },
    LspDiagnosticsVirtualTextInformation  = { fg = c.yellow },
    LspDiagnosticsVirtualTextWarning      = { fg = c.orange_warn },
    LspDiagnosticsWarning                 = { fg = c.orange_warn },

    -- LSP references / codelens
    LspReferenceRead    = { bg = c.black1, bold = true },
    LspReferenceText    = { bg = c.black1, bold = true },
    LspReferenceWrite   = { bg = c.black1, bold = true },
    LspCodeLens         = { fg = c.gray2, italic = true },
    LspCodeLensSeparator= { fg = c.gray_punc },
    LspInlayHint        = { fg = c.gray2, bg = c.bg_cursorline, italic = true },
    LspSignatureActiveParameter = { fg = c.orange, bold = true },

    -- ─── nvim-cmp ───────────────────────────────────────────────
    CmpItemAbbrDeprecated    = { fg = c.comment, strikethrough = true },
    CmpDocumentation         = { fg = c.fg },
    CmpDocumentationBorder   = { fg = c.gray2, bg = c.bg_float },
    CmpItemAbbr              = { fg = c.fg },
    CmpItemAbbrMatch         = { fg = c.blue_type, bold = true },
    CmpItemAbbrMatchFuzzy    = { fg = c.blue_type },
    CmpItemMenu              = { fg = c.pink },
    CmpItemKind              = { fg = c.green_func },
    CmpItemKindText          = { fg = c.fg },
    CmpItemKindMethod        = { fg = c.blue_type },
    CmpItemKindFunction      = { fg = c.green_func },
    CmpItemKindConstructor   = { fg = c.yellow },
    CmpItemKindField         = { fg = c.white },
    CmpItemKindVariable      = { fg = c.white },
    CmpItemKindClass         = { fg = c.red_key_w },
    CmpItemKindInterface     = { fg = c.blue_type },
    CmpItemKindModule        = { fg = c.blue_type },
    CmpItemKindProperty      = { fg = c.white },
    CmpItemKindUnit          = { fg = c.orange },
    CmpItemKindValue         = { fg = c.orange },
    CmpItemKindEnum          = { fg = c.blue_type },
    CmpItemKindKeyword       = { fg = c.pink },
    CmpItemKindSnippet       = { fg = c.green_func },
    CmpItemKindColor         = { fg = c.orange },
    CmpItemKindFile          = { fg = c.yellow },
    CmpItemKindReference     = { fg = c.pink },
    CmpItemKindFolder        = { fg = c.yellow },
    CmpItemKindEnumMember    = { fg = c.orange },
    CmpItemKindConstant      = { fg = c.orange },
    CmpItemKindStruct        = { fg = c.blue_type },
    CmpItemKindEvent         = { fg = c.red_key_w },
    CmpItemKindOperator      = { fg = c.red_key_w },
    CmpItemKindTypeParameter = { fg = c.blue_type },

    -- ─── blink.cmp (modern cmp replacement) ─────────────────────
    BlinkCmpMenu          = { fg = c.fg, bg = c.black },
    BlinkCmpMenuBorder    = { fg = c.gray2, bg = c.black },
    BlinkCmpMenuSelection = { fg = c.fg, bg = c.gray1 },
    BlinkCmpScrollBarThumb= { bg = c.gray2 },
    BlinkCmpScrollBarGutter= { bg = c.black },
    BlinkCmpLabel         = { fg = c.fg },
    BlinkCmpLabelDeprecated = { fg = c.comment, strikethrough = true },
    BlinkCmpLabelMatch    = { fg = c.blue_type, bold = true },
    BlinkCmpKind          = { fg = c.green_func },
    BlinkCmpDoc           = { fg = c.fg, bg = c.bg_float },
    BlinkCmpDocBorder     = { fg = c.gray2, bg = c.bg_float },
    BlinkCmpDocSeparator  = { fg = c.gray_punc },
    BlinkCmpSignatureHelp = { fg = c.fg, bg = c.bg_float },

    -- ─── Telescope ──────────────────────────────────────────────
    TelescopeBorder         = { fg = c.white,      bg = bg(c.bg) },
    TelescopeMatching       = { fg = c.blue_type,  bold = true },
    TelescopePromptPrefix   = { fg = c.green_func },
    TelescopeSelection      = { fg = c.fg,    bg = c.gray1 },
    TelescopeSelectionCaret = { fg = c.pink },
    TelescopeMultiSelection = { fg = c.pink },
    TelescopeNormal         = { fg = c.fg, bg = bg(c.bg) },
    TelescopePreviewTitle   = { fg = c.green_func },
    TelescopePromptTitle    = { fg = c.pink },
    TelescopeResultsTitle   = { fg = c.blue_type },
    TelescopePromptCounter  = { fg = c.comment },

    -- ─── fzf-lua ────────────────────────────────────────────────
    FzfLuaBorder     = { fg = c.white },
    FzfLuaTitle      = { fg = c.pink },
    FzfLuaHeaderBind = { fg = c.green_func },
    FzfLuaHeaderText = { fg = c.blue_type },
    FzfLuaPathColNr  = { fg = c.orange },
    FzfLuaPathLineNr = { fg = c.yellow },
    FzfLuaBufName    = { fg = c.white },
    FzfLuaBufNr      = { fg = c.orange },
    FzfLuaBufFlagCur = { fg = c.pink },
    FzfLuaBufFlagAlt = { fg = c.blue_type },
    FzfLuaTabTitle   = { fg = c.blue_type },
    FzfLuaTabMarker  = { fg = c.orange },

    -- ─── neo-tree ───────────────────────────────────────────────
    NeoTreeNormal          = { fg = c.white1, bg = c.black },
    NeoTreeNormalNC        = { fg = c.white1, bg = c.black },
    NeoTreeDimText         = { fg = c.comment },
    NeoTreeRootName        = { fg = c.yellow, bold = true },
    NeoTreeFileName        = { fg = c.white1 },
    NeoTreeFileNameOpened  = { fg = c.pink, italic = true },
    NeoTreeFilterTerm      = { fg = c.green_func },
    NeoTreeIndentMarker    = { fg = c.comment },
    NeoTreeExpander        = { fg = c.comment },
    NeoTreeGitAdded        = { fg = c.diff_add },
    NeoTreeGitConflict     = { fg = c.red_err },
    NeoTreeGitDeleted      = { fg = c.red_err },
    NeoTreeGitIgnored      = { fg = c.comment },
    NeoTreeGitModified     = { fg = c.diff_change },
    NeoTreeGitUntracked    = { fg = c.orange_warn },
    NeoTreeGitUnstaged     = { fg = c.orange_warn },
    NeoTreeGitStaged       = { fg = c.diff_add },
    NeoTreeFloatBorder     = { fg = c.gray2 },
    NeoTreeFloatTitle      = { fg = c.pink },
    NeoTreeTabActive       = { fg = c.fg, bold = true },
    NeoTreeTabInactive     = { fg = c.comment },
    NeoTreeTabSeparatorActive  = { fg = c.pink },
    NeoTreeTabSeparatorInactive= { fg = c.comment },
    NeoTreeVertSplit       = { fg = c.black },
    NeoTreeWinSeparator    = { fg = c.black },
    NeoTreeEndOfBuffer     = { fg = c.non_text },
    NeoTreeStatusLine      = { fg = c.comment, bg = c.black },
    NeoTreeSignColumn      = { bg = c.black },
    NeoTreeCursorLine      = { bg = c.bg_cursorline },
    NeoTreeDirectoryName   = { fg = c.white1 },
    NeoTreeDirectoryIcon   = { fg = c.orange },
    NeoTreeFileIcon        = { fg = c.comment },
    NeoTreeSymbolicLinkTarget = { fg = c.yellow },

    -- ─── nvim-tree ──────────────────────────────────────────────
    NvimTreeNormal           = { fg = c.white1, bg = c.black },
    NvimTreeNormalNC         = { bg = c.black },
    NvimTreeCursorLine       = { fg = c.line_nr, bg = c.black1 },
    NvimTreeRootFolder       = { fg = c.yellow, bold = true },
    NvimTreeFolderIcon       = { fg = c.comment },
    NvimTreeFolderName       = { fg = c.white1 },
    NvimTreeOpenedFolderName = { fg = c.white1, italic = true },
    NvimTreeEmptyFolderName  = { fg = c.yellow, italic = true },
    NvimTreeExecFile         = { fg = c.green },
    NvimTreeImageFile        = { fg = c.pink },
    NvimTreeSpecialFile      = { fg = c.orange },
    NvimTreeSymlink          = { fg = c.yellow },
    NvimTreeIndentMarker     = { fg = c.comment },
    NvimTreeVertSplit        = { fg = c.black },
    NvimTreeEndOfBuffer      = { fg = c.non_text },
    NvimTreeGitDirty         = { fg = c.diff_add },
    NvimTreeGitStaged        = { fg = c.diff_add },
    NvimTreeGitNew           = { fg = c.diff_add },
    NvimTreeGitDeleted       = { fg = c.red_err },
    NvimTreeGitMerge         = { fg = c.diff_change },
    NvimTreeGitRenamed       = { fg = c.diff_change },

    -- ─── Gitsigns ───────────────────────────────────────────────
    GitSignsAdd              = { fg = c.green_func, bg = c.line_bg },
    GitSignsChange           = { fg = c.diff_change, bg = c.line_bg },
    GitSignsDelete           = { fg = c.red_key_w,  bg = c.line_bg },
    GitSignsAddNr            = { fg = c.green_func },
    GitSignsChangeNr         = { fg = c.diff_change },
    GitSignsDeleteNr         = { fg = c.red_key_w },
    GitSignsAddLn            = { bg = c.bg_cursorline },
    GitSignsChangeLn         = { bg = c.bg_cursorline },
    GitSignsCurrentLineBlame = { fg = c.comment, italic = true },
    GitSignsAddInline        = { bg = c.diff_add, fg = c.bg_dark },
    GitSignsDeleteInline     = { bg = c.red_err, fg = c.bg_dark },
    GitSignsChangeInline     = { bg = c.diff_change, fg = c.bg_dark },

    -- ─── Neogit ─────────────────────────────────────────────────
    NeogitBranch                = { fg = c.pink },
    NeogitRemote                = { fg = c.pink },
    NeogitHunkHeader            = { fg = c.accent, bg = c.bg_dark },
    NeogitHunkHeaderHighlight   = { fg = c.accent, bg = c.bg_dark },
    NeogitDiffContext           = { fg = c.accent, bg = c.bg },
    NeogitDiffContextHighlight  = { fg = c.accent, bg = c.bg },
    NeogitDiffAdd               = { fg = c.diff_add,  bg = c.bg_dark },
    NeogitDiffAddHighlight      = { fg = c.diff_add,  bg = c.bg_dark },
    NeogitDiffDelete            = { fg = c.red_err,   bg = c.bg_dark },
    NeogitDiffDeleteHighlight   = { fg = c.red_err,   bg = c.bg_dark },
    NeogitChangeAdded           = { fg = c.diff_add },
    NeogitChangeDeleted         = { fg = c.red_err },
    NeogitChangeModified        = { fg = c.diff_change },
    NeogitChangeRenamed         = { fg = c.diff_change },
    NeogitChangeUntracked       = { fg = c.orange_warn },
    NeogitPopupActionKey        = { fg = c.pink },
    NeogitPopupOptionKey        = { fg = c.blue_type },
    NeogitPopupSwitchKey        = { fg = c.green_func },
    NeogitPopupSectionTitle     = { fg = c.white, bold = true },

    -- ─── Diffview ───────────────────────────────────────────────
    DiffViewNormal              = { fg = c.gray2, bg = c.bg_dark },
    DiffviewFilePanelDeletion   = { fg = c.red_err },
    DiffviewFilePanelInsertion  = { fg = c.diff_add },
    DiffviewFilePanelModified   = { fg = c.diff_change },
    DiffviewStatusAdded         = { fg = c.diff_add },
    DiffviewStatusDeleted       = { fg = c.red_err },
    DiffviewStatusModified      = { fg = c.diff_change },
    DiffviewStatusRenamed       = { fg = c.diff_change },
    DiffviewStatusCopied        = { fg = c.diff_change },
    DiffviewStatusUntracked     = { fg = c.orange_warn },
    DiffviewVertSplit           = { bg = c.bg },

    -- ─── gitgutter (vim-gitgutter) ───────────────────────────────
    GitGutterAdd                = { fg = c.diff_add },
    GitGutterChange             = { fg = c.diff_change },
    GitGutterDelete             = { fg = c.red_err },
    GitGutterChangeDelete       = { fg = c.diff_change },

    -- ─── Trouble ────────────────────────────────────────────────
    TroubleNormal       = { fg = c.white },
    TroubleText         = { fg = c.white },
    TroubleTextError    = { fg = c.red_key_w },
    TroubleTextWarning  = { fg = c.orange_warn },
    TroubleTextInfo     = { fg = c.blue_type },
    TroubleTextHint     = { fg = c.white },
    TroubleError        = { fg = c.red_key_w, bg = c.line_nr },
    TroubleWarning      = { fg = c.orange_warn },
    TroubleInformation  = { fg = c.white },
    TroubleHint         = { fg = c.orange_warn },
    TroubleSignError    = { fg = c.red_key_w },
    TroubleSignWarning  = { fg = c.orange_warn },
    TroubleSignInformation = { fg = c.white },
    TroubleSignHint     = { fg = c.green },
    TroubleSignOther    = { fg = c.green },
    TroubleFile         = { fg = c.yellow },
    TroubleFoldIcon     = { fg = c.blue_type },
    TroubleCount        = { fg = c.red_key_w },
    TroubleIndent       = { fg = c.comment },
    TroubleLocation     = { fg = c.white },
    TroubleSource       = { fg = c.blue_type },
    TroubleCode         = { fg = c.orange_warn },
    TroublePreview      = { fg = c.red_key_w },

    -- ─── which-key ──────────────────────────────────────────────
    WhichKey          = { fg = c.blue_type },
    WhichKeySeperator = { fg = c.red_key_w },
    WhichKeyGroup     = { fg = c.pink },
    WhichKeyDesc      = { fg = c.white },
    WhichKeyFloat     = { bg = c.bg_dark },
    WhichKeyValue     = { fg = c.comment },
    WhichKeyBorder    = { fg = c.gray2 },

    -- ─── indent-blankline (v2 & v3) ─────────────────────────────
    IndentBlanklineChar               = { fg = c.black1, nocombine = true },
    IndentBlanklineContextChar        = { fg = c.gray2,  nocombine = true },
    IndentBlanklineSpaceChar          = { fg = c.white1 },
    IndentBlanklineSpaceCharBlankline = { fg = c.yellow },
    IblIndent                         = { fg = c.black1, nocombine = true },
    IblScope                          = { fg = c.gray_punc, nocombine = true },
    IblWhitespace                     = { fg = c.non_text },

    -- ─── indent-guides (vim-indent-guides) ──────────────────────
    IndentGuidesEven = { fg = c.white1 },
    IndentGuidesOdd  = { fg = c.comment },

    -- ─── Rainbow delimiters ─────────────────────────────────────
    RainbowDelimiterRed    = { fg = c.red_key_w },
    RainbowDelimiterOrange = { fg = c.orange },
    RainbowDelimiterYellow = { fg = c.yellow },
    RainbowDelimiterGreen  = { fg = c.green },
    RainbowDelimiterBlue   = { fg = c.blue_type },
    RainbowDelimiterViolet = { fg = c.pink },
    RainbowDelimiterCyan   = { fg = c.boolean },

    -- ─── Lualine (colours only; lualine section backgrounds set
    --              via lualine_theme.lua, not hi groups) ─────────
    -- None needed – lualine uses its own theme table.

    -- ─── Bufferline ─────────────────────────────────────────────
    BufferLineFill              = { fg = c.fg, bg = c.bg_dark, bold = true },
    BufferLineSeparator         = { fg = c.fg, bg = c.bg },
    BufferLineTab               = { fg = c.fg, bg = c.bg },
    BufferLineBackground        = { fg = c.fg, bg = c.bg },
    BufferLineBufferVisible     = { fg = c.fg, bg = c.bg },
    BufferLineCloseButton       = { fg = c.fg, bg = c.bg },
    BufferLineCloseButtonVisible= { fg = c.fg, bg = c.bg },
    BufferLineDuplicate         = { fg = c.fg, bg = c.bg },
    BufferLineDuplicateVisible  = { fg = c.fg, bg = c.bg },
    BufferLineModified          = { fg = c.fg, bg = c.bg },
    BufferLineModifiedVisible   = { fg = c.fg, bg = c.bg },
    BufferCurrent               = { fg = c.fg, bg = c.gray0 },
    BufferCurrentIndex          = { fg = c.fg, bg = c.bg },
    BufferCurrentMod            = { fg = c.yellow, bg = c.bg },
    BufferCurrentSign           = { fg = c.blue_type, bg = c.bg },
    BufferCurrentTarget         = { fg = c.red_key_w, bg = c.bg, bold = true },
    BufferInactive              = { fg = c.gray2, bg = c.bg_dark },
    BufferInactiveIndex         = { fg = c.gray2, bg = c.bg_dark },
    BufferInactiveMod           = { fg = c.yellow, bg = c.bg_dark },
    BufferInactiveSign          = { fg = c.gray2, bg = c.bg_dark },
    BufferInactiveTarget        = { fg = c.red_key_w, bg = c.bg_dark, bold = true },
    BufferVisible               = { fg = c.fg, bg = c.bg },
    BufferVisibleIndex          = { fg = c.fg, bg = c.bg },
    BufferVisibleMod            = { fg = c.yellow, bg = c.bg },
    BufferVisibleSign           = { fg = c.green,  bg = c.bg },
    BufferVisibleTarget         = { fg = c.red_key_w, bg = c.bg, bold = true },

    -- ─── Dashboard / alpha-nvim / snacks.dashboard ──────────────
    DashboardCenter   = { fg = c.white },
    DashboardFooter   = { fg = c.yellow },
    DashboardHeader   = { fg = c.green_func },
    DashboardShortCut = { fg = c.pink },
    AlphaHeader       = { fg = c.green_func },
    AlphaFooter       = { fg = c.yellow },
    AlphaShortcut     = { fg = c.pink },
    AlphaButtons      = { fg = c.white },

    -- ─── Snacks (folke/snacks.nvim) ─────────────────────────────
    SnacksNormal        = { fg = c.fg, bg = c.bg_float },
    SnacksDashboardNormal= { fg = c.fg, bg = bg(c.bg) },
    SnacksDashboardDesc  = { fg = c.comment },
    SnacksDashboardFile  = { fg = c.white },
    SnacksDashboardDir   = { fg = c.comment },
    SnacksDashboardDate  = { fg = c.blue_type },
    SnacksDashboardFooter= { fg = c.yellow },
    SnacksDashboardHeader= { fg = c.green_func },
    SnacksDashboardIcon  = { fg = c.pink },
    SnacksDashboardKey   = { fg = c.red_key_w },
    SnacksDashboardTitle = { fg = c.white, bold = true },
    SnacksDashboardSpecial={ fg = c.orange },
    SnacksIndent        = { fg = c.black1, nocombine = true },
    SnacksIndentScope   = { fg = c.gray_punc, nocombine = true },
    SnacksPickerBorder  = { fg = c.gray2 },
    SnacksPickerTitle   = { fg = c.pink },
    SnacksPickerMatch   = { fg = c.blue_type, bold = true },
    SnacksPickerSelected= { fg = c.pink },
    SnacksNotifierTitle = { fg = c.white, bold = true },
    SnacksNotifierBorder= { fg = c.gray2 },
    SnacksNotifierIconError= { fg = c.red_err },
    SnacksNotifierIconWarn = { fg = c.orange_warn },
    SnacksNotifierIconInfo = { fg = c.blue_type },
    SnacksNotifierIconDebug= { fg = c.comment },
    SnacksNotifierIconTrace= { fg = c.gray2 },

    -- ─── Noice ──────────────────────────────────────────────────
    NoiceCompletionItemKindDefault = { fg = c.fg },
    NoiceCmdlinePopup    = { fg = c.fg, bg = c.bg_float },
    NoiceCmdlinePopupBorder = { fg = c.gray2 },
    NoiceCmdlineIcon     = { fg = c.pink },
    NoiceMini            = { fg = c.fg },
    NoiceLspProgressTitle= { fg = c.pink },
    NoiceLspProgressClient={ fg = c.blue_type },
    NoiceLspProgressSpinner={ fg = c.green_func },
    NoiceFormatProgressDone  = { fg = c.green_func, bg = c.black1 },
    NoiceFormatProgressTodo  = { fg = c.comment,    bg = c.black1 },
    NoiceConfirm         = { fg = c.fg, bg = c.bg_float },
    NoiceConfirmBorder   = { fg = c.pink },

    -- ─── Notify ─────────────────────────────────────────────────
    NotifyERRORBorder = { fg = c.red_err },
    NotifyWARNBorder  = { fg = c.orange_warn },
    NotifyINFOBorder  = { fg = c.blue_type },
    NotifyDEBUGBorder = { fg = c.comment },
    NotifyTRACEBorder = { fg = c.gray2 },
    NotifyERRORIcon   = { fg = c.red_err },
    NotifyWARNIcon    = { fg = c.orange_warn },
    NotifyINFOIcon    = { fg = c.blue_type },
    NotifyDEBUGIcon   = { fg = c.comment },
    NotifyTRACEIcon   = { fg = c.gray2 },
    NotifyERRORTitle  = { fg = c.red_err, bold = true },
    NotifyWARNTitle   = { fg = c.orange_warn, bold = true },
    NotifyINFOTitle   = { fg = c.blue_type, bold = true },
    NotifyDEBUGTitle  = { fg = c.comment, bold = true },
    NotifyTRACETitle  = { fg = c.gray2, bold = true },
    NotifyERRORBody   = { fg = c.fg },
    NotifyWARNBody    = { fg = c.fg },
    NotifyINFOBody    = { fg = c.fg },
    NotifyDEBUGBody   = { fg = c.fg },
    NotifyTRACEBody   = { fg = c.fg },

    -- ─── nvim-dap ───────────────────────────────────────────────
    debugBreakpoint      = { fg = c.red_key_w, reverse = true },
    debugPc              = { bg = c.white1 },
    DapBreakpoint        = { fg = c.red_key_w },
    DapBreakpointCondition={ fg = c.orange_warn },
    DapBreakpointRejected= { fg = c.comment },
    DapLogPoint          = { fg = c.blue_type },
    DapStopped           = { fg = c.green_func },
    DapUIScope           = { fg = c.blue_type },
    DapUIType            = { fg = c.pink },
    DapUIModifiedValue   = { fg = c.orange, bold = true },
    DapUIDecoration      = { fg = c.blue_type },
    DapUIThread          = { fg = c.green_func },
    DapUIStoppedThread   = { fg = c.blue_type },
    DapUIFrameName       = { fg = c.white },
    DapUISource          = { fg = c.pink },
    DapUILineNumber      = { fg = c.blue_type },
    DapUIFloatBorder     = { fg = c.gray2 },
    DapUIWatchesEmpty    = { fg = c.red_err },
    DapUIWatchesValue    = { fg = c.green_func },
    DapUIWatchesError    = { fg = c.red_err },
    DapUIBreakpointsPath = { fg = c.blue_type },
    DapUIBreakpointsInfo = { fg = c.green_func },
    DapUIBreakpointsCurrentLine={ fg = c.green_func, bold = true },
    DapUIBreakpointsLine = { fg = c.blue_type },
    DapUIBreakpointsDisabledLine={ fg = c.comment },
    DapUICurrentFrameName= { fg = c.green_func, bold = true },

    -- ─── flash.nvim ─────────────────────────────────────────────
    FlashBackdrop   = { fg = c.comment },
    FlashCurrent    = { fg = c.bg, bg = c.orange, bold = true },
    FlashLabel      = { fg = c.bg, bg = c.pink, bold = true },
    FlashMatch      = { bg = c.black1 },
    FlashPrompt     = { fg = c.fg, bg = c.bg_dark },
    FlashPromptIcon = { fg = c.pink, bg = c.bg_dark },

    -- ─── leap.nvim ──────────────────────────────────────────────
    LeapMatch         = { fg = c.bg, bg = c.pink, bold = true },
    LeapLabelPrimary  = { fg = c.bg, bg = c.pink, bold = true },
    LeapLabelSecondary= { fg = c.bg, bg = c.blue_type, bold = true },
    LeapBackdrop      = { fg = c.comment },

    -- ─── mini.nvim ──────────────────────────────────────────────
    MiniAnimateCursor   = { reverse = true, nocombine = true },
    MiniClueDescGroup   = { fg = c.pink },
    MiniClueDescSingle  = { fg = c.white },
    MiniClueSeparator   = { fg = c.gray_punc },
    MiniClueTitle       = { fg = c.white, bold = true },
    MiniCompletionActiveParameter = { underline = true },
    MiniCursorword      = { underline = true },
    MiniDepsChangeAdded = { fg = c.diff_add },
    MiniDepsChangeRemoved= { fg = c.red_err },
    MiniDepsMsgBreaking = { fg = c.orange_warn },
    MiniDepsPlaceholder = { fg = c.comment },
    MiniDepsTitle       = { fg = c.white, bold = true },
    MiniDepsTitleError  = { fg = c.red_err, bold = true },
    MiniDepsTitleSame   = { fg = c.comment },
    MiniDepsTitleUpdate = { fg = c.green_func, bold = true },
    MiniDiffOverAdd     = { bg = c.bg_cursorline },
    MiniDiffOverChange  = { bg = c.bg_cursorline },
    MiniDiffOverContext = { bg = c.bg_cursorline },
    MiniDiffOverDelete  = { bg = c.bg_cursorline },
    MiniDiffSignAdd     = { fg = c.green_func, bg = c.line_bg },
    MiniDiffSignChange  = { fg = c.diff_change, bg = c.line_bg },
    MiniDiffSignDelete  = { fg = c.red_key_w, bg = c.line_bg },
    MiniHipatternsFixme = { fg = c.bg, bg = c.red_err, bold = true },
    MiniHipatternsHack  = { fg = c.bg, bg = c.orange_warn, bold = true },
    MiniHipatternsNote  = { fg = c.bg, bg = c.blue_type, bold = true },
    MiniHipatternsTodo  = { fg = c.bg, bg = c.yellow, bold = true },
    MiniIconsAzure      = { fg = c.blue_type },
    MiniIconsBlue       = { fg = c.blue_type },
    MiniIconsCyan       = { fg = c.boolean },
    MiniIconsGreen      = { fg = c.green_func },
    MiniIconsGrey       = { fg = c.gray2 },
    MiniIconsOrange     = { fg = c.orange },
    MiniIconsPurple     = { fg = c.boolean },
    MiniIconsRed        = { fg = c.red_key_w },
    MiniIconsYellow     = { fg = c.yellow },
    MiniIndentscopeSymbol= { fg = c.gray_punc, nocombine = true },
    MiniJump            = { fg = c.bg, bg = c.pink },
    MiniJump2dSpot      = { fg = c.pink, bold = true, nocombine = true },
    MiniJump2dSpotAhead = { fg = c.blue_type, bg = c.bg, nocombine = true },
    MiniJump2dSpotUnique= { fg = c.yellow, bold = true, nocombine = true },
    MiniMapNormal       = { fg = c.fg, bg = c.bg_sidebar },
    MiniMapSymbolCount  = { fg = c.gray_punc },
    MiniMapSymbolLine   = { fg = c.pink },
    MiniMapSymbolView   = { fg = c.blue_type },
    MiniNotifyBorder    = { fg = c.gray2 },
    MiniNotifyNormal    = { fg = c.fg, bg = c.bg_float },
    MiniNotifyTitle     = { fg = c.white, bold = true },
    MiniOperatorExchangeFrom = { reverse = true },
    MiniPickBorder      = { fg = c.gray2 },
    MiniPickBorderBusy  = { fg = c.orange_warn },
    MiniPickBorderText  = { fg = c.pink },
    MiniPickHeader      = { fg = c.blue_type },
    MiniPickIconDirectory={ fg = c.orange },
    MiniPickIconFile    = { fg = c.white },
    MiniPickMatchCurrent= { bg = c.black1 },
    MiniPickMatchMarked = { bg = c.bg_visual },
    MiniPickMatchRanges = { fg = c.blue_type, bold = true },
    MiniPickNormal      = { fg = c.fg, bg = bg(c.bg) },
    MiniPickPreviewLine = { bg = c.bg_cursorline },
    MiniPickPreviewRegion={ reverse = true },
    MiniPickPromptCaret = { fg = c.green_func },
    MiniPickPromptNormal= { fg = c.fg, bg = c.bg_dark },
    MiniPickPromptPrefix= { fg = c.pink },
    MiniPickPromptQuery = { fg = c.fg },
    MiniStatuslineModeNormal = { fg = c.bg, bg = c.green_func, bold = true },
    MiniStatuslineModeInsert = { fg = c.bg, bg = c.blue_type, bold = true },
    MiniStatuslineModeVisual = { fg = c.bg, bg = c.pink, bold = true },
    MiniStatuslineModeReplace= { fg = c.bg, bg = c.red_key_w, bold = true },
    MiniStatuslineModeCommand= { fg = c.bg, bg = c.orange_warn, bold = true },
    MiniStatuslineModeOther  = { fg = c.bg, bg = c.yellow, bold = true },
    MiniStatuslineDevinfo    = { fg = c.gray2, bg = c.black1 },
    MiniStatuslineFilename   = { fg = c.fg,   bg = c.gray0 },
    MiniStatuslineFileinfo   = { fg = c.gray2, bg = c.black1 },
    MiniStatuslineInactive   = { fg = c.comment, bg = c.bg_dark },
    MiniSurround        = { fg = c.bg, bg = c.orange },
    MiniTablineCurrent  = { fg = c.fg, bg = c.gray0, bold = true },
    MiniTablineHidden   = { fg = c.gray2, bg = c.bg_dark },
    MiniTablineModifiedCurrent= { fg = c.yellow, bg = c.gray0, bold = true },
    MiniTablineModifiedHidden = { fg = c.yellow, bg = c.bg_dark },
    MiniTablineModifiedVisible= { fg = c.yellow, bg = c.bg },
    MiniTablineTabpagesection = { fg = c.bg_dark, bg = c.green_func },
    MiniTablineVisible  = { fg = c.fg, bg = c.bg },
    MiniTestEmphasis    = { bold = true },
    MiniTestFail        = { fg = c.red_err, bold = true },
    MiniTestPass        = { fg = c.green_func, bold = true },
    MiniTrailspace      = { bg = c.red_err },

    -- ─── Harpoon ────────────────────────────────────────────────
    HarpoonBorder   = { fg = c.gray2 },
    HarpoonWindow   = { fg = c.fg, bg = c.bg_float },

    -- ─── Startify / vim-startify ────────────────────────────────
    StartifyEndOfBuffer = { fg = c.non_text },
    StartifyNumber      = { fg = c.red_key_w },
    StartifySelect      = { fg = c.comment },
    StartifyBracket     = { fg = c.white },
    StartifySpecial     = { fg = c.yellow },
    StartifyVar         = { fg = c.comment },
    StartifyPath        = { fg = c.comment },
    StartifyFile        = { fg = c.blue_type },
    StartifySlash       = { fg = c.comment },
    StartifyHeader      = { fg = c.blue_type },
    StartifyFooter      = { fg = c.pink },
    StartifySection     = { fg = c.pink },

    -- ─── NERDTree ───────────────────────────────────────────────
    NERDTreeUp              = { fg = c.yellow },
    NERDTreeDir             = { fg = c.blue_type },
    NERDTreeOpenable        = { fg = c.comment },
    NERDTreeClosable        = { fg = c.red_key_w },
    NERDTreeIgnore          = { fg = c.comment },
    NERDTreeHelpKey         = { fg = c.white },
    NERDTreeHelpTitle       = { fg = c.pink },
    NERDTreeToggleOn        = { fg = c.green_func },
    NERDTreeToggleOff       = { fg = c.orange },
    NERDTreeHelpCommand     = { fg = c.yellow },
    NERDTreeFile            = { fg = c.white },
    NERDTreeLinkTarget      = { fg = c.blue_type },
    NERDTreeLinkFile        = { fg = c.green_func },
    NERDTreeLinkDir         = { fg = c.pink },
    NERDTreeNodeDelimiters  = { fg = c.comment },
    NERDTreeDirSlash        = { fg = c.comment },
    NERDTreeExecFile        = { fg = c.green_func },
    NERDTreeRO              = { fg = c.orange },
    NERDTreeBookmarkName    = { fg = c.orange },
    NERDTreeFlags           = { fg = c.red_key_w },
    NERDTreeCWD             = { fg = c.red_key_w },
    NERDTreeBookmarksLeader = { fg = c.blue_type },
    NERDTreeBookmarksHeader = { fg = c.red_key_w },
    NERDTreeBookmark        = { fg = c.orange },
    NERDTreePart            = { fg = c.orange },
    NERDTreePartFile        = { fg = c.blue_type },
    NERDTreeCurrentNode     = { fg = c.comment },

    -- ─── oil.nvim ───────────────────────────────────────────────
    OilDir        = { fg = c.blue_type },
    OilDirIcon    = { fg = c.orange },
    OilLink       = { fg = c.yellow },
    OilLinkTarget = { fg = c.comment },
    OilFile       = { fg = c.white },
    OilSocket     = { fg = c.boolean },
    OilCreate     = { fg = c.green_func },
    OilDelete     = { fg = c.red_err },
    OilChange     = { fg = c.diff_change },
    OilMove       = { fg = c.orange_warn },
    OilCopy       = { fg = c.blue_type },

    -- ─── Aerial (symbol outline) ────────────────────────────────
    AerialLine      = { bg = c.bg_cursorline },
    AerialLineNC    = { bg = c.bg_cursorline },
    AerialGuide     = { fg = c.comment },
    AerialNormal    = { fg = c.fg, bg = c.bg_sidebar },
    AerialClass     = { fg = c.red_key_w },
    AerialFunction  = { fg = c.green_func },
    AerialMethod    = { fg = c.green_func },
    AerialVariable  = { fg = c.white },
    AerialConstant  = { fg = c.pink },
    AerialField     = { fg = c.white },
    AerialModule    = { fg = c.blue_type },
    AerialNamespace = { fg = c.blue_type },
    AerialStruct    = { fg = c.green_func },
    AerialEnum      = { fg = c.blue_type },
    AerialEnumMember= { fg = c.orange },
    AerialInterface = { fg = c.blue_type },

    -- ─── Symbols-outline ────────────────────────────────────────
    FocusedSymbol   = { fg = c.pink, bg = c.black1 },
    SymbolsOutlineConnector = { fg = c.comment },

    -- ─── Illuminate (word highlights) ───────────────────────────
    illuminatedWord            = { bg = c.black1 },
    illuminatedCurWord         = { bg = c.black1 },
    IlluminatedWordText        = { bg = c.black1 },
    IlluminatedWordRead        = { bg = c.black1 },
    IlluminatedWordWrite       = { bg = c.black1 },

    -- ─── Marks.nvim ─────────────────────────────────────────────
    MarkSignHL     = { fg = c.orange_warn },
    MarkSignNumHL  = { fg = c.orange_warn },
    MarkVirtTextHL = { fg = c.comment },

    -- ─── Scrollbar ──────────────────────────────────────────────
    ScrollbarHandle        = { bg = c.black1 },
    ScrollbarCursorHandle  = { bg = c.black1 },
    ScrollbarCursor        = { fg = c.gray_punc },
    ScrollbarSearchHandle  = { fg = c.orange, bg = c.black1 },
    ScrollbarSearch        = { fg = c.orange },
    ScrollbarErrorHandle   = { fg = c.red_err, bg = c.black1 },
    ScrollbarError         = { fg = c.red_err },
    ScrollbarWarnHandle    = { fg = c.orange_warn, bg = c.black1 },
    ScrollbarWarn          = { fg = c.orange_warn },
    ScrollbarInfoHandle    = { fg = c.blue_type, bg = c.black1 },
    ScrollbarInfo          = { fg = c.blue_type },
    ScrollbarHintHandle    = { fg = c.green_func, bg = c.black1 },
    ScrollbarHint          = { fg = c.green_func },
    ScrollbarMiscHandle    = { fg = c.gray2, bg = c.black1 },
    ScrollbarMisc          = { fg = c.gray2 },

    -- ─── Fidget (LSP progress) ───────────────────────────────────
    FidgetTitle  = { fg = c.blue_type, bold = true },
    FidgetTask   = { fg = c.comment },

    -- ─── Helpview / render-markdown ──────────────────────────────
    RenderMarkdownH1   = { fg = c.pink, bold = true },
    RenderMarkdownH2   = { fg = c.blue_type, bold = true },
    RenderMarkdownH3   = { fg = c.green_func, bold = true },
    RenderMarkdownH4   = { fg = c.yellow, bold = true },
    RenderMarkdownH5   = { fg = c.orange_warn, bold = true },
    RenderMarkdownH6   = { fg = c.white },
    RenderMarkdownH1Bg = { bg = c.bg_cursorline },
    RenderMarkdownH2Bg = { bg = c.bg_cursorline },
    RenderMarkdownH3Bg = { bg = c.bg_cursorline },
    RenderMarkdownCode = { bg = c.black1 },
    RenderMarkdownCodeInline = { fg = c.orange },
    RenderMarkdownBullet     = { fg = c.red_key_w },
    RenderMarkdownChecked    = { fg = c.green_func },
    RenderMarkdownUnchecked  = { fg = c.gray_punc },
    RenderMarkdownLink       = { fg = c.pink, underline = true },
    RenderMarkdownQuote      = { fg = c.comment, italic = true },
    RenderMarkdownTableHead  = { fg = c.white, bold = true },
    RenderMarkdownTableRow   = { fg = c.fg },
    RenderMarkdownTableFill  = { fg = c.gray_punc },

    -- ─── Headlines.nvim ─────────────────────────────────────────
    Headline1  = { fg = c.pink,      bg = c.bg_cursorline, bold = true },
    Headline2  = { fg = c.blue_type, bg = c.bg_cursorline, bold = true },
    Headline3  = { fg = c.green_func,bg = c.bg_cursorline, bold = true },
    Headline4  = { fg = c.yellow,    bg = c.bg_cursorline, bold = true },
    CodeBlock  = { bg = c.black1 },
    Dash       = { fg = c.gray_punc },
    Quote      = { fg = c.comment },

    -- ─── Copilot ────────────────────────────────────────────────
    CopilotSuggestion = { fg = c.comment, italic = true },

    -- ─── CodeActionMenu ─────────────────────────────────────────
    CodeActionMenuWarningMessageText   = { fg = c.orange_warn },
    CodeActionMenuWarningMessageBorder = { fg = c.red_key_w },
    CodeActionMenuMenuIndex            = { fg = c.blue_type },
    CodeActionMenuMenuKind             = { fg = c.green },
    CodeActionMenuMenuTitle            = { fg = c.white },
    CodeActionMenuMenuDisabled         = { fg = c.comment },
    CodeActionMenuMenuSelection        = { fg = c.blue_type },
    CodeActionMenuDetailsTitle         = { fg = c.white },
    CodeActionMenuDetailsLabel         = { fg = c.yellow },
    CodeActionMenuDetailsPreferred     = { fg = c.green },
    CodeActionMenuDetailsDisabled      = { fg = c.comment },
    CodeActionMenuDetailsUndefined     = { fg = c.comment },

    -- ─── Flutter tools ──────────────────────────────────────────
    FlutterWidgetGuides = { fg = c.gray2 },

    -- ─── CMake ──────────────────────────────────────────────────
    cmakeCommand              = { fg = c.white },
    cmakeArguments            = { fg = c.white },
    cmakeKWvariable_watch     = { fg = c.white },
    cmakeKWproject            = { fg = c.pink },
    cmakeGeneratorExpressions = { fg = c.pink },
    cmakeVariable             = { fg = c.white },
    cmakeKWuse_mangled_mesa   = { fg = c.fg, italic = true },

    -- ─── Python (vim-python-pep8-indent etc.) ───────────────────
    pythonConditional = { fg = c.red_key_w },
    pythonException   = { fg = c.pink },
    pythonFunction    = { fg = c.green_func },
    pythonInclude     = { fg = c.red_key_w },
    pythonOperator    = { fg = c.red_key_w },
    pythonStatement   = { fg = c.white },
    pythonBoolean     = { fg = c.white },

    -- ─── Lazy.nvim ──────────────────────────────────────────────
    LazyNormal        = { fg = c.fg, bg = c.bg_float },
    LazyBorder        = { fg = c.gray2 },
    LazyButton        = { fg = c.fg, bg = c.black1 },
    LazyButtonActive  = { fg = c.fg, bg = c.gray0, bold = true },
    LazyComment       = { fg = c.comment },
    LazyCommit        = { fg = c.green_func },
    LazyCommitIssue   = { fg = c.orange_warn },
    LazyCommitType    = { fg = c.blue_type },
    LazyDir           = { fg = c.blue_type },
    LazyError         = { fg = c.red_err },
    LazyH1            = { fg = c.pink, bold = true },
    LazyH2            = { fg = c.white, bold = true },
    LazyInfo          = { fg = c.blue_type },
    LazyLocal         = { fg = c.diff_add },
    LazyProgressDone  = { fg = c.green_func, bold = true },
    LazyProgressTodo  = { fg = c.gray2 },
    LazyProp          = { fg = c.comment },
    LazyReasonCmd     = { fg = c.yellow },
    LazyReasonEvent   = { fg = c.blue_type },
    LazyReasonFt      = { fg = c.green_func },
    LazyReasonImport  = { fg = c.orange_warn },
    LazyReasonKeys    = { fg = c.pink },
    LazyReasonPlugin  = { fg = c.blue_type },
    LazyReasonRuntime = { fg = c.orange_warn },
    LazyReasonSource  = { fg = c.blue_type },
    LazyReasonStart   = { fg = c.green_func },
    LazyReasonURI     = { fg = c.yellow, underline = true },
    LazySpecial       = { fg = c.pink },
    LazyTaskError     = { fg = c.red_err },
    LazyTaskOutput    = { fg = c.fg },
    LazyTitle         = { fg = c.white, bold = true },
    LazyUrl           = { fg = c.yellow, underline = true },
    LazyWarning       = { fg = c.orange_warn },

    -- ─── Mason ──────────────────────────────────────────────────
    MasonNormal         = { fg = c.fg, bg = c.bg_float },
    MasonHeader         = { fg = c.bg, bg = c.pink, bold = true },
    MasonHeaderSecondary= { fg = c.bg, bg = c.green_func, bold = true },
    MasonHighlight      = { fg = c.blue_type },
    MasonHighlightBlock = { fg = c.bg, bg = c.blue_type },
    MasonHighlightBlockBold = { fg = c.bg, bg = c.blue_type, bold = true },
    MasonHighlightSecondary      = { fg = c.green_func },
    MasonHighlightBlockSecondary = { fg = c.bg, bg = c.green_func },
    MasonHighlightBlockBoldSecondary = { fg = c.bg, bg = c.green_func, bold = true },
    MasonLink           = { fg = c.yellow, underline = true },
    MasonMuted          = { fg = c.comment },
    MasonMutedBlock     = { fg = c.bg, bg = c.comment },
    MasonError          = { fg = c.red_err },
    MasonWarning        = { fg = c.orange_warn },
    MasonHeading        = { fg = c.white, bold = true },

    -- ─── Todo-comments ──────────────────────────────────────────
    TodoFgFIX  = { fg = c.red_err },
    TodoFgTODO = { fg = c.blue_type },
    TodoFgHACK = { fg = c.orange_warn },
    TodoFgWARN = { fg = c.orange_warn },
    TodoFgPERF = { fg = c.boolean },
    TodoFgNOTE = { fg = c.green_func },
    TodoFgTEST = { fg = c.pink },
    TodoBgFIX  = { fg = c.bg, bg = c.red_err, bold = true },
    TodoBgTODO = { fg = c.bg, bg = c.blue_type, bold = true },
    TodoBgHACK = { fg = c.bg, bg = c.orange_warn, bold = true },
    TodoBgWARN = { fg = c.bg, bg = c.orange_warn, bold = true },
    TodoBgPERF = { fg = c.bg, bg = c.boolean, bold = true },
    TodoBgNOTE = { fg = c.bg, bg = c.green_func, bold = true },
    TodoBgTEST = { fg = c.bg, bg = c.pink, bold = true },
    TodoSignFIX  = { fg = c.red_err },
    TodoSignTODO = { fg = c.blue_type },
    TodoSignHACK = { fg = c.orange_warn },
    TodoSignWARN = { fg = c.orange_warn },
    TodoSignPERF = { fg = c.boolean },
    TodoSignNOTE = { fg = c.green_func },
    TodoSignTEST = { fg = c.pink },

    -- ─── Fidget spinner ─────────────────────────────────────────
    FidgetTask  = { fg = c.comment },
    FidgetTitle = { fg = c.blue_type, bold = true },

    -- ─── Neotest ────────────────────────────────────────────────
    NeotestAdapterName = { fg = c.pink, bold = true },
    NeotestDir         = { fg = c.blue_type },
    NeotestExpandMarker= { fg = c.comment },
    NeotestFailed      = { fg = c.red_err },
    NeotestFile        = { fg = c.yellow },
    NeotestFocused     = { fg = c.orange_warn, bold = true },
    NeotestIndent      = { fg = c.comment },
    NeotestMarked      = { fg = c.orange_warn, bold = true },
    NeotestNamespace   = { fg = c.blue_type },
    NeotestPassed      = { fg = c.green_func },
    NeotestRunning     = { fg = c.yellow },
    NeotestSelect      = { fg = c.pink },
    NeotestSkipped     = { fg = c.comment },
    NeotestTarget      = { fg = c.pink },
    NeotestTest        = { fg = c.white },
    NeotestUnknown     = { fg = c.comment },
    NeotestWatching    = { fg = c.blue_type },

    -- ─── nvim-surround / vim-surround ───────────────────────────
    -- (uses IncSearch / Visual by default – nothing extra needed)
  }

  -- Merge and return
  return vim.tbl_deep_extend("force", editor, plugins)
end

return M
